remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3Q455XWS5F
title: U-M EFDC Open Source Projects
description: Accelerating innovations through code to improve mental health outcomes across our communities.
